services:
  prettier:
    image: prettier
    build:
      context: node_modules/.pnpm/prettier@3.9.6/node_modules/prettier
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
